#
# Dependabot Configuration Files
#
# List for "package-ecosystem": https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-
#
version: 2

updates:
  # Checks for: GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Checks for: Dockerfile (but not docker-compose)
  - package-ecosystem: "docker"
    directories:
      - "/images/*"
    schedule:
      interval: "weekly"
