name: Build and Push to Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      CONTAINER_NAME: 'ubuntu-dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Required for Docker Buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Recommended for building multi-arch images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # NOTE: We use Docker Hub rather than GitHub's container registry because the docker/build-push-action action
      #   apparently produces container images that GitHub's container registry doesn't fully support (it will result
      #   in an unknown/unknown architecture). The only workaround is to disable provenance (see
      #   https://github.com/docker/build-push-action/issues/820#issuecomment-1482113833) but provenance improves
      #   the "trustworthiness" of the image. So, I'd rather leave it on.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          # NOTE: We only use "latest" as tag as users will always want to use the latest (and thus only) image.
          #   There should be no point in using an older image. Also, this way we don't need to cleanup old images.
          tags:  ${{ vars.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_NAME }}:latest

      # Uses the repo's README to update the overview on DockerHub.
      # NOTE: Requires a Docker Hub token with "Read, Write, Delete" rights.
      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_NAME }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
